apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: replik
    stage: dev
spec:
  ports:
  - name: http
    port: 80               # port expose par docker  (pas le port dans le container)
    targetPort: 80
  - name: theia
    port: 3000    # port expose par docker  (pas le port dans le container)
    targetPort: 3000
  selector:                     # key/value, label permettant de definir le pod cible (doit etre danslabels du pod)
    app: replik 
  type: LoadBalancer
